// This file is auto-generated by env.config.js
// Do not edit this file directly - change values in .env file or set environment variables

export const environment = {
  production: false,
  bungie: {
    apiKey: 'API_KEY',
    apiRoot: 'https://www.bungie.net/Platform',
    authUrl: 'https://www.bungie.net/en/OAuth/Authorize',
    tokenUrl: 'https://www.bungie.net/Platform/App/OAuth/token/',
    clientId: 'CLIENT_ID',
    clientSecret: 'CLIENT_SECRET',
    redirectUrl: 'https://localhost:4433/auth/callback',
    redirectConfig: {
      useCurrentHost: false,
      protocol: 'https',
      host: 'localhost',
      port: '4433',
      path: '/auth/callback'
    }
  },
  logging: {
    minLevel: 'DEBUG',
    emitters: {
      console: true,
      remote: true,
      file: true
    },
    remoteEndpoints: [
      'http://localhost:3000/api/logs'
    ],
    file: {
      enabled: true,
      basePath: './data/logs/',
      folderNamePrefix: 'destiny-app-',
      maxSize: 10 * 1024 * 1024,
      maxFiles: 5,
      compress: true,
      rotationPeriod: 'daily',
      filenamePattern: '{prefix}log-{date}.json'
    },
    offline: {
      enabled: true,
      maxBufferSize: 50,
      syncWhenOnline: true
    },
    maxStoredLogs: 100,
    includeStacksInProduction: false,
    appVersion: '1.0.0',
    filters: {
      excludeSources: ['polling-service', 'heartbeat'],
      custom: {
        environment: 'development',
        clientId: 'destiny-inventory-manager'
      }
    }
  }
};

// Production environment
export const productionEnvironment = {
  production: true,
  bungie: {
    apiKey: 'API_KEY',
    apiRoot: 'https://www.bungie.net/Platform',
    authUrl: 'https://www.bungie.net/en/OAuth/Authorize',
    tokenUrl: 'https://www.bungie.net/Platform/App/OAuth/token/',
    clientId: 'CLIENT_ID',
    clientSecret: 'CLIENT_SECRET',
    redirectUrl: 'https://localhost:4433/auth/callback',
    redirectConfig: {
      useCurrentHost: false,
      protocol: 'https',
      host: 'localhost',
      port: '4433',
      path: '/auth/callback'
    }
  },
  logging: {
    minLevel: 'INFO',
    emitters: {
      console: false,
      remote: true,
      file: true
    },
    remoteEndpoints: [
      'https://api.yourproduction.com/logs'
    ],
    file: {
      enabled: true,
      basePath: '/var/log/destiny-app/',
      folderNamePrefix: 'prod-',
      maxSize: 100 * 1024 * 1024,
      compress: true,
      maxFiles: 30,
      rotationPeriod: 'daily',
      filenamePattern: '{prefix}{date}.log.gz'
    },
    offline: {
      enabled: true,
      maxBufferSize: 200,
      syncWhenOnline: true
    },
    maxStoredLogs: 50,
    includeStacksInProduction: false,
    appVersion: '1.0.0',
    filters: {
      excludeSources: ['polling-service', 'heartbeat', 'analytics'],
      custom: {
        environment: 'production',
        clientId: 'destiny-inventory-manager'
      }
    }
  }
};